"""Initial migration

Revision ID: 3f85115db7aa
Revises: 
Create Date: 2026-02-25 14:02:48.730983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f85115db7aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_encrypted', sa.String(length=500), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_usuario'), ['usuario'], unique=True)

    op.create_table('pacientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('codigo_paciente', sa.String(length=50), nullable=True),
    sa.Column('motivo', sa.String(length=100), nullable=True),
    sa.Column('medico_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pacientes_codigo_paciente'), ['codigo_paciente'], unique=True)

    op.create_table('pantallas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('codigo_vinculacion', sa.String(length=6), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('ultima_conexion', sa.DateTime(), nullable=True),
    sa.Column('vinculada_at', sa.DateTime(), nullable=True),
    sa.Column('recepcionista_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['recepcionista_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pantallas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pantallas_device_id'), ['device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pantallas_numero'), ['numero'], unique=True)

    op.create_table('turnos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('medico_id', sa.String(length=36), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('codigo_turno', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turnos_codigo_turno'), ['codigo_turno'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turnos_codigo_turno'))

    op.drop_table('turnos')
    with op.batch_alter_table('pantallas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pantallas_numero'))
        batch_op.drop_index(batch_op.f('ix_pantallas_device_id'))

    op.drop_table('pantallas')
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pacientes_codigo_paciente'))

    op.drop_table('pacientes')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_usuario'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
