"""pantalla_recepciones many-to-many

Revision ID: 969594c9e24a
Revises: 3f85115db7aa
Create Date: 2026-03-03 14:48:03.574254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969594c9e24a'
down_revision = '3f85115db7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantalla_recepciones',
    sa.Column('pantalla_id', sa.String(length=36), nullable=False),
    sa.Column('recepcionista_id', sa.String(length=36), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('asignado_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pantalla_id'], ['pantallas.id'], ),
    sa.ForeignKeyConstraint(['recepcionista_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('pantalla_id', 'recepcionista_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pantalla_recepciones')
    # ### end Alembic commands ###
